### ISSUE TITLE
What are the plans for trice?

### ISSUE THREAD

**Issue by ggarber** [alfredh/rew#1]
Looks cool.  Any plan to maintain this code or integrate it in the main libre repo?

**Comment by alfredh** [comment]
the first goal is to develop a more flexible ICE-stack, that can support all types
of ICE like Full-ice, Trickle-ice, ICE-lite and protocols like UDP and TCP.

you can help by compiling and testing the library on different platforms

for example this ICE-client (https://github.com/alfredh/reicec) can be installed on
two different hosts and you can use it to test connectivity checks between them.

after a period of review and testing, it will probably be merge into libre.
