### ISSUE TITLE
Loopback pairing and IPv4 link-local pairing

### ISSUE THREAD

**Issue by lgrahl** [alfredh/rew#13]
As discussed in #11, I would like to reduce the amount of pairs by only pairing loopback with loopback and IPv4 link-local with IPv4 link-local (IPv6 link-local is already covered by #12).

I would propose the following changes to `trice_conf` to make this possible by configuration:

```
/** ICE Configuration */
struct trice_conf {
	[...]
	bool pair_loopback;      /**< Enable pairing of loopback addresses with other non-loopback addresses */
	bool pair_ipv4_linklocal;      /**< Enable pairing of IPv4 link-local addresses with other non-link-local addresses */
};
```

`pair_loopback` and `pair_ipv4_linklocal` would be `true` by default.

Thoughts? :)

**Comment by alfredh** [comment]
I think IPv4 link local is not so commonly used, so I would not care so much about that.

perhaps one extra boolean flag is enough, to enable pairing optimization ?

for example;
```
bool optimize_pairing;  /* Name TBD */
```

by enabling this flag, the ICE stack will optimize as much as possible, perhaps
also other (yet unknown) combinations ...?

Alfred

**Comment by lgrahl** [comment]
Maybe we'll leave out the IPv4 link-local case for now (it indeed is pretty uncommon now) and just add this:

```c
bool optimize_loopback_pairing
```

This would allow for more fine-granular control in case we add further optimisations in the future.

**Comment by alfredh** [comment]
okay that sounds great, let us start with that one first. We can also add more things
later, if there is a usecase for it.

also, it is good to keep the positive logic in the boolean, the code becomes
easier to read
