### ISSUE TITLE
Remote role unclear

### ISSUE THREAD

**Issue by lgrahl** [alfredh/rew#7]
Now that we've switched from a boolean role (controlling - yes/no) to an explicit role using an enumerator, there's one open issue [here](https://github.com/alfredh/rew/blob/e5903f9f742db41aaafb16e98335a8addfe5d559/src/trice/stunsrv.c#L234):

What should happen if `remote_role == ICE_ROLE_UNKNOWN`?

**Comment by alfredh** [comment]
according to the ICE rfc:

https://tools.ietf.org/html/rfc5245#section-7.1.2.2

```
The agent MUST include the ICE-CONTROLLED attribute in the request if
   it is in the controlled role, and MUST include the ICE-CONTROLLING
   attribute in the request if it is in the controlling role. 
```

I think we can check this in stunsrv.c and if either is missing, reject
the request with an error response.

one more thing to consider; if the user-agent detects that the remote endpoint
is `icelite` it must select role=Controlling and remote role = Controlled.

**Comment by lgrahl** [comment]
Okay, sounds good. Do you want to resolve this yourself? Although I'm a bit busy at the moment, you can assign me as well in case you're busy, too.

**Comment by alfredh** [comment]
@lgrahl I pushed a fix for this.
