### ISSUE TITLE
Silent failure when combined username fragments too long

### ISSUE THREAD

**Issue by lgrahl** [alfredh/rew#9]
`username_buf` has storage for 64 characters and the following call fails silently in case that buffer is full: https://github.com/alfredh/rew/blob/af107e66a145c53d9b97ee0ed02406e518d475fc/src/trice/connchk.c#L291

I guess it would make sense to either make this buffer dynamic or return an error in case it's too large to be copied.

**Comment by alfredh** [comment]
hi @lgrahl thanks for reporting :)
